FightScheduler/urls.py
from . import views #
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
#from .views home, home_files
from FightScheduler.models import StatusCode,AccountType,Role,Address,Person,Organization,Service,AllowableService,Affiliation,PersonalInformation,Career,NonBoxerInfo,Waiver,WaiverRequirement,Signature,SignedWaiver,MedicalCert,ServiceEnrollment,MatchResultCode,Series,Show,Match,MatchRound# @MODEL_IMPORTS@
from rest_framework import routers, serializers, viewsets



# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# @START - REGISTER DEFAULT VIEWS@
router.register(r'StatusCode', views.StatusCodeViewSet)
router.register(r'AccountType', views.AccountTypeViewSet)
router.register(r'Role', views.RoleViewSet)
router.register(r'Address', views.AddressViewSet)
router.register(r'Person', views.PersonViewSet)
router.register(r'Organization', views.OrganizationViewSet)
router.register(r'Service', views.ServiceViewSet)
router.register(r'AllowableService', views.AllowableServiceViewSet)
router.register(r'Affiliation', views.AffiliationViewSet)
router.register(r'PersonalInformation', views.PersonalInformationViewSet)
router.register(r'Career', views.CareerViewSet)
router.register(r'NonBoxerInfo', views.NonBoxerInfoViewSet)
router.register(r'Waiver', views.WaiverViewSet)
router.register(r'WaiverRequirement', views.WaiverRequirementViewSet)
router.register(r'Signature', views.SignatureViewSet)
router.register(r'SignedWaiver', views.SignedWaiverViewSet)
router.register(r'MedicalCert', views.MedicalCertViewSet)
router.register(r'ServiceEnrollment', views.ServiceEnrollmentViewSet)
router.register(r'MatchResultCode', views.MatchResultCodeViewSet)
router.register(r'Series', views.SeriesViewSet)
router.register(r'Show', views.ShowViewSet)
router.register(r'Match', views.MatchViewSet)
router.register(r'MatchRound', views.MatchRoundViewSet)
# @END - REGISTER DEFAULT VIEWS@

app_name = 'fightscheduler'
urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
	path('', views.main, name='main'),
	path('main', views.main, name='main'),
	path('languageSelector/<str:langCode>/', views.languageSelector, name='languageSelector'),
    path('<int:pk>/personDetailView', views.PersonView.as_view(), name='personDetailView'),
    path('personCreate/', views.PersonCreate.as_view(), name='personCreate'),
    path('personUpdate/', views.PersonUpdate.as_view(), name='personUpdate'),
    path('personalInfoCreate/', views.PersonalInfoCreate.as_view(), name='personalInfoCreate'),
    path('personalInfoUpdate/', views.PersonalInfoUpdate.as_view(), name='personalInfoUpdate'),
    path('careerCreate/', views.CareerCreate.as_view(), name='careerCreate'),
    path('careerUpdate/', views.CareerUpdate.as_view(), name='careerUpdate'),
    path('otherInfoCreate/', views.OtherInfoCreate.as_view(), name='otherInfoCreate'),
    path('otherInfoUpdate/', views.OtherInfoUpdate.as_view(), name='otherInfoUpdate'),
    path('showCreate/', views.ShowCreate.as_view(), name='showCreate'),
	path('matchCreate/', views.MatchCreate.as_view(), name='matchCreate'),
    path('matchUpdate/', views.MatchUpdate.as_view(), name='matchUpdate'),
	path('availabilityCreate/', views.AvailabilityScheduleCreate.as_view(), name='availabilityCreate'),
    path('availabilityUpdate/', views.AvailabilityScheduleUpdate.as_view(), name='availabilityUpdate'),

	path('<int:pk>/editPersonalInformation/', views.editPersonalInformation, name='editPersonalInformation'),
	path('registerClub/', views.clubRegistration, name='clubRegistration'),
	path('editProfile/<int:pk>/', views.editProfile, name='editProfile'),
	path('editClubDetails/<int:organizationID>/', views.editClubDetails, name='editClubDetails'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include(router.urls)),

    path('index/', views.IndexView.as_view(), name='index'),

    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urls.py
from . import views #
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
#from .views home, home_files
from FightScheduler.models import StatusCode,AccountInfo,AccountType,Role,Address,Person,Organization,Service,AllowableService,Affiliation,PersonalInformation,Career,NonBoxerInfo,Waiver,WaiverRequirement,Signature,SignedWaiver,MedicalCert,ServiceEnrollment,MatchResultCode,Series,Show,Match,MatchRound,AvailabilitySchedule# @MODEL_IMPORTS@
from rest_framework import routers, serializers, viewsets



# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# @START - REGISTER DEFAULT VIEWS@
router.register(r'StatusCode', views.StatusCodeViewSet)
router.register(r'AccountInfo', views.AccountInfoViewSet)
router.register(r'AccountType', views.AccountTypeViewSet)
router.register(r'Role', views.RoleViewSet)
router.register(r'Address', views.AddressViewSet)
router.register(r'Person', views.PersonViewSet)
router.register(r'Organization', views.OrganizationViewSet)
router.register(r'Service', views.ServiceViewSet)
router.register(r'AllowableService', views.AllowableServiceViewSet)
router.register(r'Affiliation', views.AffiliationViewSet)
router.register(r'PersonalInformation', views.PersonalInformationViewSet)
router.register(r'Career', views.CareerViewSet)
router.register(r'NonBoxerInfo', views.NonBoxerInfoViewSet)
router.register(r'Waiver', views.WaiverViewSet)
router.register(r'WaiverRequirement', views.WaiverRequirementViewSet)
router.register(r'Signature', views.SignatureViewSet)
router.register(r'SignedWaiver', views.SignedWaiverViewSet)
router.register(r'MedicalCert', views.MedicalCertViewSet)
router.register(r'ServiceEnrollment', views.ServiceEnrollmentViewSet)
router.register(r'MatchResultCode', views.MatchResultCodeViewSet)
router.register(r'Series', views.SeriesViewSet)
router.register(r'Show', views.ShowViewSet)
router.register(r'Match', views.MatchViewSet)
router.register(r'MatchRound', views.MatchRoundViewSet)
router.register(r'AvailabilitySchedule', views.AvailabilityScheduleViewSet)
# @END - REGISTER DEFAULT VIEWS@

app_name = 'fightscheduler'
urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
	path('', views.main, name='main'),
	path('main', views.main, name='main'),
	path('languageSelector/<str:langCode>/', views.languageSelector, name='languageSelector'),
    path('<int:pk>/personDetailView', views.PersonView.as_view(), name='personDetailView'),
    path('personCreate/', views.PersonCreate.as_view(), name='personCreate'),
    path('personUpdate/', views.PersonUpdate.as_view(), name='personUpdate'),
    path('personalInfoCreate/', views.PersonalInfoCreate.as_view(), name='personalInfoCreate'),
    path('personalInfoUpdate/', views.PersonalInfoUpdate.as_view(), name='personalInfoUpdate'),
    path('careerCreate/', views.CareerCreate.as_view(), name='careerCreate'),
    path('careerUpdate/', views.CareerUpdate.as_view(), name='careerUpdate'),
    path('otherInfoCreate/', views.OtherInfoCreate.as_view(), name='otherInfoCreate'),
    path('otherInfoUpdate/', views.OtherInfoUpdate.as_view(), name='otherInfoUpdate'),
	path('matchCreate/', views.MatchCreate.as_view(), name='matchCreate'),
    path('matchUpdate/', views.MatchUpdate.as_view(), name='matchUpdate'),
	path('availabilityCreate/', views.AvailabilityScheduleCreate.as_view(), name='availabilityCreate'),
    path('availabilityUpdate/', views.AvailabilityScheduleUpdate.as_view(), name='availabilityUpdate'),

	path('<int:pk>/editPersonalInformation/', views.editPersonalInformation, name='editPersonalInformation'),
	path('registerClub/', views.clubRegistration, name='clubRegistration'),
	path('editProfile/<int:pk>/', views.editProfile, name='editProfile'),
	path('editClubDetails/<int:organizationID>/', views.editClubDetails, name='editClubDetails'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include(router.urls)),

    path('index/', views.IndexView.as_view(), name='index'),

    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

webapps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


urlpatterns = [
    path('FightScheduler/', include('FightScheduler.urls')),
    path('admin/', admin.site.urls),
	#url(r'^api-auth/', include('rest_framework.urls')),
]

FightScheduler/templates/availabilitySchedule.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

{% if user.is_authenticated %}

		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="/FightScheduler/">Home</a></li>
			<li class="breadcrumb-item active" aria-current="page">Schedule Availability</li>
		  </ol>
		</nav>

		<h5 class="card-title">Schedule Availability</h5>
		{% if form.AvailabilityScheduleID != None %}
			<p class="card-text">Update Availability</p>
			<form action="{% url 'fightscheduler:availabilityUpdate' %}" method="post">
		{% else %}
			<p class="card-text">Set Availability</p>
			<form action="{% url 'fightscheduler:availabilityCreate' %}" method="post">
		{% endif %}
			{% csrf_token %}

			<div class="d-none">
				{{ form.AvailabilityScheduleID }}
			</div>

			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.callToConfirmAvailability}}callToConfirmAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.sundayAMAvailability}}sundayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.mondayAMAvailability}}mondayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.tuesdayAMAvailability}}tuesdayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.wednesdayAMAvailability}}wednesdayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.thursdayAMAvailability}}thursdayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.fridayAMAvailability}}fridayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.saturdayAMAvailability}}saturdayAMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.sundayPMAvailability}}sundayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.mondayPMAvailability}}mondayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.tuesdayPMAvailability}}tuesdayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.wednesdayPMAvailability}}wednesdayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.thursdayPMAvailability}}thursdayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.fridayPMAvailability}}fridayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.saturdayPMAvailability}}saturdayPMAvailability
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableJanuary}}availableJanuary
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableFebruary}}availableFebruary
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableMarch}}availableMarch
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableApril}}availableApril
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableMay}}availableMay
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableJune}}availableJune
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableJuly}}availableJuly
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableAugust}}availableAugust
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableSeptember}}availableSeptember
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableOctober}}availableOctober
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableNovember}}availableNovember
				</label>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					{{ form.availableDecember}}availableDecember
				</label>
			</div>
			<div class="form-group">
				{% if form..errors %}<div class="alert alert-danger">{{ form..errors}}</div>{% endif %}
					<label for="></label>
					{{ form. }}
				<small id="" class="form-text text-muted"></small>
			</div>
								
			{% if form.AvailabilityScheduleID != None %}
				<button type="submit" class="btn btn-primary" style="float:right">Update Account</button>
			{% else %}
				<button type="submit" class="btn btn-primary" style="float:right">Create Account</button>
			{% endif %}					
		</form>
{% endif %}
{% endblock %}

FightScheduler/templates/career.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}


{% if user.is_authenticated %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
	<li class="breadcrumb-item"><a href="/FightScheduler/">Home</a></li>
	<li class="breadcrumb-item"><a href="/FightScheduler/personUpdate/">Account Info</a></li>
	<li class="breadcrumb-item">
		{% if request.session.accountInfo.personalInfoID == None %}
			<a href="/FightScheduler/personalInfoCreate/">Personal Info</a>
		{% else %}
			<a href="/FightScheduler/personalInfoUpdate/">Personal Info</a>
		{% endif %}
	</li>
	<li class="breadcrumb-item" active" aria-current="page">Career Info</li>
	{% if request.session.accountInfo.isCoach == True or request.session.accountInfo.isOfficial == True or request.session.accountInfo.isOwner == True or request.session.accountInfo.isBoxingOntarioAdmin == True %}
		{% if request.session.accountInfo.otherInfoID != None %}
				<li class="breadcrumb-item"></li>
						<a href="/FightScheduler/otherInfoUpdate/">Other Info</a>
				</li>
		{% else %}
				<li class="breadcrumb-item"></li>
						<a href="/FightScheduler/otherInfoCreate/">Other Info</a>
				</li>				
		{% endif %}
	{% endif %}
  </ol>
</nav>

<p class="card-text">{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field }} {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
</p>

			{% if request.session.accountInfo.careerID != None %}
                <h5 class="card-title">Update Career Information</h5>
				<form action="{% url 'fightscheduler:careerUpdate' %}" method="post">
			{% else %}
                <h5 class="card-title">Tell Us Your Boxing Career History</h5>
				<form action="{% url 'fightscheduler:careerCreate' %}" method="post">
			{% endif %}
					 {% csrf_token %}
					{{ form.CareerID }}

					<div class="form-group">
						{% if form.genderCode.errors %}<div class="alert alert-danger">{{ form.genderCode.errors}}</div>{% endif %}
						<label for="genderCode">Gender Category</label>
						{{ form.genderCode }}
						<small id="" class="form-text text-muted"> </small>
					</div>
					<div class="form-group">
						{% if form.dateofBirth.errors %}<div class="alert alert-danger">{{ form.dateofBirth.errors}}</div>{% endif %}
						<label for="dateofBirth">Date of Birth</label>
						{{ form.dateofBirth }}
						<small id="" class="form-text text-muted">MM/DD/YYYY - Strictly for classification purposes</small>
					</div>
					<div class="form-group">
						{% if form.height.errors %}<div class="alert alert-danger">{{ form.height.errors}}</div>{% endif %}
						<label for="height">Height (cms)</label>
						{{ form.height }}
						<small id="" class="form-text text-muted"></small>
					</div>
					<div class="form-group">
						{% if form.currentWeight.errors %}<div class="alert alert-danger">{{ form.currentWeight.errors}}</div>{% endif %}
						<label for=currentWeight"> Current Weight</label>
						{{ form.currentWeight }}
						<small id="" class="form-text text-muted"></small>
					</div>
					<div class="form-group">
						{% if form.amateurBouts.errors %}<div class="alert alert-danger">{{ form.amateurBouts.errors}}</div>{% endif %}
						<label for=amateurBouts"> Amateur Bouts</label>
						{{ form.amateurBouts }}
						<small id="" class="form-text text-muted"></small>
					</div>
					<div class="form-group">
						{% if form.amateurWins.errors %}<div class="alert alert-danger">{{ form.amateurWins.errors}}</div>{% endif %}
						<label for=amateurWins"> Amateur Wins</label>
						{{ form.amateurWins }}
						<small id="" class="form-text text-muted"></small>
					</div>
					<div class="form-group form-check">
						<label class="form-check-label">
						  {{ form.previousProfessionalCombatSportInvolvement }} I have previous or current involvement in professional boxing, kickboxing or any combat sport
						</label>
					</div>
					{% if form.previousProfessionalCombatSportInvolvement.value == True %}
						<div id="professionalExperience" class="collapse show">
					{% else %}
						<div id="professionalExperience" class="collapse">
					{% endif %}
					<small id="" class="form-text text-muted"></small>
					{% if form.professionalYears.errors %}<div class="alert alert-danger">{{ form.professionalYears.errors}}</div>{% endif %}
					<label for=professionalYears"> Professional Years</label>
					{{ form.professionalYears }}
					<small id="" class="form-text text-muted"></small>
					{% if form.professionalBouts.errors %}<div class="alert alert-danger">{{ form.professionalBouts.errors}}</div>{% endif %}
					<label for=professionalBouts"> Professional Bouts</label>
					{{ form.professionalBouts }}
					<small id="" class="form-text text-muted"></small>
					{% if form.professionalWins.errors %}<div class="alert alert-danger">{{ form.professionalWins.errors}}</div>{% endif %}
					<label for=professionalWins"> Professional Wins</label>
					{{ form.professionalWins }}
					</div>

					<div class="form-group form-check">
						<label class="form-check-label">
						  {{ form.previousCombatSportInvolvementInOtherCountry }} I have previous or current involvement in amateur or professional boxing, kickboxing or any combat sport in another country
						</label>
					</div>

					{% if form.previousCombatSportInvolvementInOtherCountry.value == True %}
						<div id="foreignExperience" class="collapse show">
					{% else %}
						<div id="foreignExperience" class="collapse">
					{% endif %}
					{% if form.previousYearsOutofCountry.errors %}<div class="alert alert-danger">{{ form.previousYearsOutofCountry.errors}}</div>{% endif %}
					<label for=previousYearsOutofCountry"> Previous Years Out of Country</label>
					{{ form.previousYearsOutofCountry }}
					<small id="" class="form-text text-muted"></small>
					{% if form.previousBoutsOutofCountry.errors %}<div class="alert alert-danger">{{ form.previousBoutsOutofCountry.errors}}</div>{% endif %}
					<label for=previousBoutsOutofCountry"> Previous Bouts Out of Country</label>
					{{ form.previousBoutsOutofCountry }}
					<small id="" class="form-text text-muted"></small>
					{% if form.previousWinsOutofCountry.errors %}<div class="alert alert-danger">{{ form.previousWinsOutofCountry.errors}}</div>{% endif %}
					<label for=previousWinsOutofCountry"> Previous Wins Out of Country</label>
					{{ form.previousWinsOutofCountry }}
					<small id="" class="form-text text-muted"></small>
					</div>

					<div class="form-group form-check">
						<label class="form-check-label">
						  {{ form.previousAmateurCombatSportInvolvement }} I have previous or current involvement in amateur boxing, kickboxing or any combat sport
						</label>
					</div>

					{% if form.previousAmateurCombatSportInvolvement.value == True %}
						<div id="previousNonBoxingOntarioExperience" class="collapse show">
					{% else %}
						<div id="previousNonBoxingOntarioExperience" class="collapse">
					{% endif %}
					{% if form.previousAmateurBouts.errors %}<div class="alert alert-danger">{{ form.previousAmateurBouts.errors}}</div>{% endif %}
					<label for=previousAmateurBouts"> Previous Amateur Bouts</label>
					{{ form.previousAmateurBouts }}
					<small id="" class="form-text text-muted"></small>
					{% if form.previousAmateurWins.errors %}<div class="alert alert-danger">{{ form.previousAmateurWins.errors}}</div>{% endif %}
					<label for=previousAmateurWins"> Previous Amateur Wins</label>
					{{ form.previousAmateurWins }}
					<small id="" class="form-text text-muted"></small>
					{% if form.previousAmateurKOs.errors %}<div class="alert alert-danger">{{ form.previousAmateurKOs.errors}}</div>{% endif %}
					<label for=previousAmateurKOs"> Previous Amateur KOs</label>
					{{ form.previousAmateurKOs }}
					<small id="" class="form-text text-muted"></small>
					{% if form.previousAmateurTKOs.errors %}<div class="alert alert-danger">{{ form.previousAmateurTKOs.errors}}</div>{% endif %}
					<label for=previousAmateurTKOs"> Previous Amateur TKOs</label>
					{{ form.previousAmateurTKOs }}
					<small id="" class="form-text text-muted"></small>
					</div>
					

					{% if form.instance.careerID %}
					<button type="submit" class="btn btn-primary" style="float:right">Update</button>
					{% else %}
					<button type="submit" class="btn btn-primary" style="float:right">Save</button>
					{% endif %}

				</form>
{% else %}
	Please re-login or register from the home page.
{% endif %}
{% endblock %}

FightScheduler/templates/main.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Welcome</h1>

<div class="row">

	{% if user.is_authenticated %}
		{% if request.session.accountInfo.isOfficial == True %}
		<div class="col-md-4">
			<div class="card mb-2">
				<img class="card-img-top" src="{% static "FightScheduler/img/payam-tahery-raZ1Ga6PLr4-unsplash-small.jpg" %}" alt"Individual Registration">
				<div class="card-body">
					<h5 class="card-title">Register Match</h5>
					<p class="card-text">Register results of a match</p>
					<a href="{% url 'fightscheduler:matchCreate' %}" class="btn btn-primary">Register</a>
				</div>
			</div>
		</div>
		{% endif %}
		
		{% if request.session.accountInfo.isCoach == True %}
		<div class="col-md-4">
			<div class="card mb-2">
				<img class="card-img-top" src="{% static "FightScheduler/img/david-guliciuc-o2zrjlM5s5o-unsplash-small.jpg" %}" alt"Club Registration">
				<div class="card-body">
					<h5 class="card-title">Setup Training Schedule</h5>
					<p class="card-text">Schedule training with boxers</p>
					<a href="{% url 'fightscheduler:clubRegistration' %}"
					   class="btn btn-primary">
						Schedule
					</a>
				</div>
			</div>
		</div>
		{%endif %}

		{% if request.session.accountInfo.isBoxer == True or request.session.accountInfo.isCoach == True or request.session.accountInfo.isOfficial == True %}
		<div class="col-md-4">
			<div class="card mb-2">
				<img class="card-img-top" src="{% static "FightScheduler/img/david-guliciuc-o2zrjlM5s5o-unsplash-small.jpg" %}" alt"Club Registration">
				<div class="card-body">
					<h5 class="card-title">Update Your Availability</h5>
					<p class="card-text">Update your availability schedule</p>
					<a href="{% url 'fightscheduler:availabilityCreate' %}"
					   class="btn btn-primary">
						Update
					</a>
				</div>
			</div>
		</div>
		{%endif %}

		{% if request.session.accountInfo.isOwner == True %}
		<div class="col-md-4">
			<div class="card mb-2">
				<img class="card-img-top" src="{% static "FightScheduler/img/david-guliciuc-o2zrjlM5s5o-unsplash-small.jpg" %}" alt"Club Registration">
				<div class="card-body">
					<h5 class="card-title">Update Club Info</h5>
					<p class="card-text">Update your club's info</p>
					<a href="{% url 'fightscheduler:clubRegistration' %}"
					   class="btn btn-primary">
						Update
					</a>
				</div>
			</div>
		</div>
		{%endif %}

		<div class="col-md-4">
			<div class="card mb-2">
				<img class="card-img-top" src="{% static "FightScheduler/img/payam-tahery-raZ1Ga6PLr4-unsplash-small.jpg" %}" alt"Individual Registration">
				<div class="card-body">
					<h5 class="card-title">Review Matches</h5>
					<p class="card-text">View past match results</p>
					<a href="{% url 'fightscheduler:personUpdate' %}" class="btn btn-primary">View</a>
				</div>
			</div>
		</div>
	{% endif %}
	
	
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static "FightScheduler/img/payam-tahery-raZ1Ga6PLr4-unsplash-small.jpg" %}" alt"Individual Registration">
            <div class="card-body">
				{% if user.is_authenticated %}
                <h5 class="card-title">Update Account Info</h5>
                <p class="card-text">Update Account Info</p>
					{% csrf_token %}
					<a href="{% url 'fightscheduler:personUpdate' %}" class="btn btn-primary">Update</a>
				{% else %}
                <h5 class="card-title">Individual Registration</h5>
                <p class="card-text">Register as a boxer/owner/ coach/judge/referee</p>
					{% csrf_token %}
					<a href="{% url 'fightscheduler:personCreate' %}" class="btn btn-primary">Register</a>
				{% endif %}
            </div>
        </div>
    </div>

</div>
{% endblock %}