FightScheduler/urls.py
from . import views #
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
#from .views home, home_files
from FightScheduler.models import StatusCode,AccountType,Role,Address,Person,Organization,Service,AllowableService,Affiliation,PersonalInformation,Career,NonBoxerInfo,Waiver,WaiverRequirement,Signature,SignedWaiver,MedicalCert,ServiceEnrollment,MatchResultCode,Series,Show,Match,MatchRound# @MODEL_IMPORTS@
from rest_framework import routers, serializers, viewsets



# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# @START - REGISTER DEFAULT VIEWS@
router.register(r'StatusCode', views.StatusCodeViewSet)
router.register(r'AccountType', views.AccountTypeViewSet)
router.register(r'Role', views.RoleViewSet)
router.register(r'Address', views.AddressViewSet)
router.register(r'Person', views.PersonViewSet)
router.register(r'Organization', views.OrganizationViewSet)
router.register(r'Service', views.ServiceViewSet)
router.register(r'AllowableService', views.AllowableServiceViewSet)
router.register(r'Affiliation', views.AffiliationViewSet)
router.register(r'PersonalInformation', views.PersonalInformationViewSet)
router.register(r'Career', views.CareerViewSet)
router.register(r'NonBoxerInfo', views.NonBoxerInfoViewSet)
router.register(r'Waiver', views.WaiverViewSet)
router.register(r'WaiverRequirement', views.WaiverRequirementViewSet)
router.register(r'Signature', views.SignatureViewSet)
router.register(r'SignedWaiver', views.SignedWaiverViewSet)
router.register(r'MedicalCert', views.MedicalCertViewSet)
router.register(r'ServiceEnrollment', views.ServiceEnrollmentViewSet)
router.register(r'MatchResultCode', views.MatchResultCodeViewSet)
router.register(r'Series', views.SeriesViewSet)
router.register(r'Show', views.ShowViewSet)
router.register(r'Match', views.MatchViewSet)
router.register(r'MatchRound', views.MatchRoundViewSet)
# @END - REGISTER DEFAULT VIEWS@

app_name = 'fightscheduler'
urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
	path('', views.main, name='main'),
	path('main', views.main, name='main'),
	path('languageSelector/<str:langCode>/', views.languageSelector, name='languageSelector'),
    path('<int:pk>/personDetailView', views.PersonView.as_view(), name='personDetailView'),
    path('personCreate/', views.PersonCreate.as_view(), name='personCreate'),
    path('personUpdate/', views.PersonUpdate.as_view(), name='personUpdate'),
    path('personalInfoCreate/', views.PersonalInfoCreate.as_view(), name='personalInfoCreate'),
    path('personalInfoUpdate/', views.PersonalInfoUpdate.as_view(), name='personalInfoUpdate'),
    path('careerCreate/', views.CareerCreate.as_view(), name='careerCreate'),
    path('careerUpdate/', views.CareerUpdate.as_view(), name='careerUpdate'),
    path('otherInfoCreate/', views.OtherInfoCreate.as_view(), name='otherInfoCreate'),
    path('otherInfoUpdate/', views.OtherInfoUpdate.as_view(), name='otherInfoUpdate'),
    path('showCreate/', views.ShowCreate.as_view(), name='showCreate'),
	path('matchCreate/', views.MatchCreate.as_view(), name='matchCreate'),
    path('matchUpdate/', views.MatchUpdate.as_view(), name='matchUpdate'),
	path('availabilityCreate/', views.AvailabilityScheduleCreate.as_view(), name='availabilityCreate'),
    path('availabilityUpdate/', views.AvailabilityScheduleUpdate.as_view(), name='availabilityUpdate'),

	path('<int:pk>/editPersonalInformation/', views.editPersonalInformation, name='editPersonalInformation'),
	path('registerClub/', views.clubRegistration, name='clubRegistration'),
	path('editProfile/<int:pk>/', views.editProfile, name='editProfile'),
	path('editClubDetails/<int:organizationID>/', views.editClubDetails, name='editClubDetails'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include(router.urls)),

    path('index/', views.IndexView.as_view(), name='index'),

    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urls.py
from . import views #
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
#from .views home, home_files
from FightScheduler.models import StatusCode,AccountInfo,AccountType,Role,Address,Person,Organization,Service,AllowableService,Affiliation,PersonalInformation,Career,NonBoxerInfo,Waiver,WaiverRequirement,Signature,SignedWaiver,MedicalCert,ServiceEnrollment,MatchResultCode,Series,Show,Match,MatchRound,AvailabilitySchedule# @MODEL_IMPORTS@
from rest_framework import routers, serializers, viewsets



# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
# @START - REGISTER DEFAULT VIEWS@
router.register(r'StatusCode', views.StatusCodeViewSet)
router.register(r'AccountInfo', views.AccountInfoViewSet)
router.register(r'AccountType', views.AccountTypeViewSet)
router.register(r'Role', views.RoleViewSet)
router.register(r'Address', views.AddressViewSet)
router.register(r'Person', views.PersonViewSet)
router.register(r'Organization', views.OrganizationViewSet)
router.register(r'Service', views.ServiceViewSet)
router.register(r'AllowableService', views.AllowableServiceViewSet)
router.register(r'Affiliation', views.AffiliationViewSet)
router.register(r'PersonalInformation', views.PersonalInformationViewSet)
router.register(r'Career', views.CareerViewSet)
router.register(r'NonBoxerInfo', views.NonBoxerInfoViewSet)
router.register(r'Waiver', views.WaiverViewSet)
router.register(r'WaiverRequirement', views.WaiverRequirementViewSet)
router.register(r'Signature', views.SignatureViewSet)
router.register(r'SignedWaiver', views.SignedWaiverViewSet)
router.register(r'MedicalCert', views.MedicalCertViewSet)
router.register(r'ServiceEnrollment', views.ServiceEnrollmentViewSet)
router.register(r'MatchResultCode', views.MatchResultCodeViewSet)
router.register(r'Series', views.SeriesViewSet)
router.register(r'Show', views.ShowViewSet)
router.register(r'Match', views.MatchViewSet)
router.register(r'MatchRound', views.MatchRoundViewSet)
router.register(r'AvailabilitySchedule', views.AvailabilityScheduleViewSet)
# @END - REGISTER DEFAULT VIEWS@

app_name = 'fightscheduler'
urlpatterns = [
	path('i18n/', include('django.conf.urls.i18n')),
	path('', views.main, name='main'),
	path('main', views.main, name='main'),
	path('languageSelector/<str:langCode>/', views.languageSelector, name='languageSelector'),
    path('<int:pk>/personDetailView', views.PersonView.as_view(), name='personDetailView'),
    path('personCreate/', views.PersonCreate.as_view(), name='personCreate'),
    path('personUpdate/', views.PersonUpdate.as_view(), name='personUpdate'),
    path('personalInfoCreate/', views.PersonalInfoCreate.as_view(), name='personalInfoCreate'),
    path('personalInfoUpdate/', views.PersonalInfoUpdate.as_view(), name='personalInfoUpdate'),
    path('careerCreate/', views.CareerCreate.as_view(), name='careerCreate'),
    path('careerUpdate/', views.CareerUpdate.as_view(), name='careerUpdate'),
    path('otherInfoCreate/', views.OtherInfoCreate.as_view(), name='otherInfoCreate'),
    path('otherInfoUpdate/', views.OtherInfoUpdate.as_view(), name='otherInfoUpdate'),
	path('matchCreate/', views.MatchCreate.as_view(), name='matchCreate'),
    path('matchUpdate/', views.MatchUpdate.as_view(), name='matchUpdate'),
	path('availabilityCreate/', views.AvailabilityScheduleCreate.as_view(), name='availabilityCreate'),
    path('availabilityUpdate/', views.AvailabilityScheduleUpdate.as_view(), name='availabilityUpdate'),

	path('<int:pk>/editPersonalInformation/', views.editPersonalInformation, name='editPersonalInformation'),
	path('registerClub/', views.clubRegistration, name='clubRegistration'),
	path('editProfile/<int:pk>/', views.editProfile, name='editProfile'),
	path('editClubDetails/<int:organizationID>/', views.editClubDetails, name='editClubDetails'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include(router.urls)),

    path('index/', views.IndexView.as_view(), name='index'),

    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

webapps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


urlpatterns = [
    path('FightScheduler/', include('FightScheduler.urls')),
    path('admin/', admin.site.urls),
	#url(r'^api-auth/', include('rest_framework.urls')),
]

webapps/templates/base.html
{% load i18n %}
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'fightscheduler:main' %}">{% trans "Fight Scheduler" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
		<nav class="nav">
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto nav justify-content-end">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'fightscheduler:languageSelector' 'EN' %}">{% trans "Language" %}</a>
					</li>
					<li class="nav-item">
						{% block content %}
						<div class="dropdown">
						{% if user.is_authenticated %}
							<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{% trans "My Info" %}
							</button>
							  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
								<a class="dropdown-item" href="{% url 'fightscheduler:personUpdate' %}">Account Info</a>
								{% if request.session.accountInfo.personalInfoID != None %}
									<a class="dropdown-item" href="{% url 'fightscheduler:personalInfoUpdate' %}">Personal Info</a>
								{% else %}
									<a class="dropdown-item" href="{% url 'fightscheduler:personalInfoCreate' %}">Personal Info</a>
								{% endif %}
								{% if request.session.accountInfo.isBoxer == True %}
									{% if request.session.accountInfo.careerID != None %}
										<a class="dropdown-item" href="{% url 'fightscheduler:careerUpdate' %}">Career Info</a>
									{% else %}
										<a class="dropdown-item" href="{% url 'fightscheduler:careerCreate' %}">Career Info</a>
									{% endif %}
								{% endif %}
								{% if request.session.accountInfo.isCoach == True or request.session.accountInfo.isOfficial == True or request.session.accountInfo.isOwner == True or request.session.accountInfo.isBoxingOntarioAdmin == True %}
									{% if request.session.accountInfo.otherInfoID != None %}
										<a class="dropdown-item" href="{% url 'fightscheduler:otherInfoUpdate' %}">Other Info</a>
									{% else %}
										<a class="dropdown-item" href="{% url 'fightscheduler:otherInfoCreate' %}">Other Info</a>
									{% endif %}
								{% endif %}
								<a class="dropdown-item" href="{% url 'fightscheduler:logout' %}">Logout</a>
							</div>
						{% else %}
							<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{% trans "Login" %}
							</button>
							<div class="dropdown-menu">
								{% if form.errors %}
									<p>Your username and password didn't match. Please try again.</p>
								{% endif %}
								<form class="px-4 py-3" action="{% url 'fightscheduler:login' %}" method="post">
									{% csrf_token %}
									<div class="form-group">
										<label for="id_username">Username:</label>
										<input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
									</div>
									<div class="form-group">
										<label for="id_password">Password:</label>
										<input type="password" name="password" autocomplete="current-password" required id="id_password">
									</div>
									<div class="form-check">
										<input type="checkbox" class="form-check-input" id="dropdownCheck">
										<label class="form-check-label" for="dropdownCheck">Remember me</label>
									</div>
									<button type="submit" class="btn btn-primary">Sign in</button>
									<input type="hidden" name="next" value="{{ next }}" />
								</form>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'fightscheduler:personCreate">New around here? Sign up</a>
							
							<a class="dropdown-item" href="{% url 'fightscheduler:password_reset' %}">Forgot password?</a>
							</div>
						{% endif %}
						</div>
						{% endblock %}
					</li>
				</ul>
			</div>
		</nav>
	</div>
</nav>

<div class="container">
    {% block page_content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>